# Generated by Django 2.1.5 on 2019-12-15 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wms', '0002_auto_20191215_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='lines',
            field=models.ManyToManyField(blank=True, null=True, to='wms.OrderLine'),
        ),
    ]
